import fs from 'fs';
import path from 'path';
import { excelParser } from '../excel/excel.parser.js';
import { rulesEngine } from '../rules/rules.engine.js';
import { aiService } from '../ai/ai.service.js';
import { telegramService } from '../telegram/telegram.service.js';
import { generateSampleExcel } from './generate-sample.js';
import { config } from '../config/config.js';
import { logger } from '../logger/logger.js';

async function runLocalTest() {
  logger.info('--- 🧪 STARTING LOCAL PIPELINE INTEGRATION TEST ---');
  
  const inputDir = path.resolve(process.cwd(), 'data', 'input');
  const outputDir = path.resolve(process.cwd(), 'data', 'output');

  // 1. Ensure local directories exist
  if (!fs.existsSync(inputDir)) {
    fs.mkdirSync(inputDir, { recursive: true });
  }
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // 2. Scan for .xlsx files in data/input
  let files = fs.readdirSync(inputDir)
    .filter(f => f.endsWith('.xlsx'))
    .map(f => {
      const filePath = path.join(inputDir, f);
      const stat = fs.statSync(filePath);
      return { name: f, path: filePath, mtime: stat.mtimeMs };
    })
    .sort((a, b) => b.mtime - a.mtime);

  if (files.length === 0) {
    logger.info(`No Excel spreadsheets found in '${inputDir}'. Automatically seeding a 'sample_ledger.xlsx' template...`);
    await generateSampleExcel(); // Generates sample_ledger.xlsx at root

    const sampleSource = path.resolve(process.cwd(), 'sample_ledger.xlsx');
    const sampleDest = path.join(inputDir, 'sample_ledger.xlsx');
    
    fs.copyFileSync(sampleSource, sampleDest);
    
    // Clean up sample_ledger.xlsx in root generated by generateSampleExcel
    fs.unlinkSync(sampleSource);

    files = [{
      name: 'sample_ledger.xlsx',
      path: sampleDest,
      mtime: Date.now()
    }];
  }

  const latestLocalFile = files[0];
  const fileName = latestLocalFile.name;
  const samplePath = latestLocalFile.path;

  // 3. Read local file buffer
  logger.info({ samplePath }, 'Reading spreadsheet into memory buffer...');
  const fileBuffer = fs.readFileSync(samplePath);

  // 4. Excel Module: Parse workbook
  const parseResult = await excelParser.parseBuffer(fileBuffer, fileName);
  const { transactions, errors: parsingErrors } = parseResult;

  logger.info(`Successfully parsed ${transactions.length} transactions with ${parsingErrors.length} ingestion errors.`);

  // 5. Rules Engine: Evaluate business validation rules
  const alerts = rulesEngine.evaluate(transactions);
  logger.info(`Rules Engine complete. Generated ${alerts.length} business alerts.`);

  // 6. Check AI keys and run AI generation
  const activeProvider = config.AI_PROVIDER;
  const hasApiKey = 
    (activeProvider === 'gemini' && config.GEMINI_API_KEY && config.GEMINI_API_KEY !== 'your_gemini_api_key_here') ||
    (activeProvider === 'openai' && config.OPENAI_API_KEY && config.OPENAI_API_KEY !== 'your_openai_api_key_here') ||
    (activeProvider === 'claude' && config.CLAUDE_API_KEY && config.CLAUDE_API_KEY !== 'your_claude_api_key_here') ||
    (activeProvider === 'openrouter' && config.OPENROUTER_API_KEY && config.OPENROUTER_API_KEY !== 'your_openrouter_api_key_here') ||
    (activeProvider === 'deepseek' && config.DEEPSEEK_API_KEY && config.DEEPSEEK_API_KEY !== 'your_deepseek_api_key_here') ||
    (activeProvider === 'groq' && config.GROQ_API_KEY && config.GROQ_API_KEY !== 'your_groq_api_key_here') ||
    (activeProvider === 'ollama');

  let reportText = '';

  if (hasApiKey) {
    logger.info({ provider: activeProvider }, 'Configured API keys detected. Invoking LIVE AI generation...');
    try {
      reportText = await aiService.generateFinancialSummary({
        fileName,
        runTimestamp: new Date().toLocaleString(),
        transactions,
        alerts,
        parsingErrors,
      });
    } catch (err) {
      logger.error({ err }, 'Live AI generation failed. Falling back to mock report.');
      reportText = generateMockAiReport(transactions, alerts, parsingErrors, fileName);
    }
  } else {
    logger.warn('No active AI Provider API Keys configured. Performing Dry Run with mock AI generation.');
    reportText = generateMockAiReport(transactions, alerts, parsingErrors, fileName);
  }

  // 7. Write final report locally for inspection (to data/output)
  const cleanFileName = fileName.replace(/\.[^/.]+$/, ""); // Strip extension
  const reportPath = path.resolve(outputDir, `${cleanFileName}_summary.md`);
  fs.writeFileSync(reportPath, reportText);
  logger.info({ reportPath }, 'Saved final report markdown inside data/output directory.');

  // 8. Check Telegram credentials and send message
  const hasTelegramKeys = 
    config.TELEGRAM_BOT_TOKEN && 
    config.TELEGRAM_BOT_TOKEN !== '1234567890:ABCdefGhIJKlmNoPQRsTUVwxyZ' &&
    config.TELEGRAM_CHAT_ID && 
    config.TELEGRAM_CHAT_ID !== '-1001234567890';

  if (hasTelegramKeys) {
    logger.info('Active Telegram bot credentials detected. Delivering report to chat...');
    try {
      await telegramService.sendReport(reportText);
      logger.info('Telegram test delivery succeeded!');
    } catch (err) {
      logger.error({ err }, 'Telegram test delivery failed.');
    }
  } else {
    logger.warn('Telegram credentials are at default settings. Skipping Telegram dispatch.');
  }

  logger.info('\n--- 📝 COMPILED REPORT PREVIEW ---');
  console.log(reportText);
  logger.info('--- 🧪 INTEGRATION TEST RUN COMPLETE ---');
}

/**
 * Generates a mock AI analysis for dry-runs.
 */
function generateMockAiReport(transactions: any[], alerts: any[], errors: any[], fileName: string = 'sample_ledger.xlsx'): string {
  const totalIncome = transactions.filter(t => t.type === 'credit').reduce((sum, t) => sum + t.amount, 0);
  const totalExpenses = transactions.filter(t => t.type === 'debit').reduce((sum, t) => sum + t.amount, 0);
  const net = totalIncome - totalExpenses;
  const netStatus = net >= 0 ? 'Surplus 🟢' : 'Deficit 🔴';
  
  const formattedErrors = errors.length > 0
    ? errors.map(e => `  - Row ${e.row}${e.invoiceNumber ? ` (Inv: ${e.invoiceNumber})` : ''}: ${e.error}`).join('\n')
    : '  - No ingestion errors. Clean file read!';

  const formattedAlerts = alerts.length > 0
    ? alerts.map((a, i) => {
        const emoji = a.severity === 'critical' ? '🔴' : a.severity === 'high' ? '🟠' : '⚠️';
        return `   ${i + 1}. ${emoji} *[${a.severity.toUpperCase()}]* ${a.ruleName}
      └ _${a.message}_
      👉 *Action:* ${
        a.ruleId === 'RULE_001' ? 'Hold payment to vendor immediately and investigate duplicate double billing.' :
        a.ruleId === 'RULE_002' ? 'Review retroactive CFO/Board authorization for single transaction overlimit.' :
        a.ruleId === 'RULE_004' ? 'Verify late-night T&E log with employee business hospitality claim forms.' :
        'Verify transaction compliance and correct ledger logging.'
      }`;
      }).join('\n\n')
    : '   - No compliance anomalies detected.';

  return `📋 *AUDIT REPORT METADATA*
-----------------------------------
• *Ingestion Date & Time*: ${new Date().toLocaleString()}
• *Source File Name*: \`${fileName}\`
• *Audit Status*: ${errors.length > 0 ? '"Processed with Ingestion Errors" ⚠️' : '"Successfully Processed (Clean Ingest)" ✅'}

---

📊 *FINANCIAL DASHBOARD*
-----------------------------------
• *Total Inflows (Revenue)*: ₹${Math.round(totalIncome).toLocaleString()}
• *Total Outflows (Expenses)*: ₹${Math.round(totalExpenses).toLocaleString()}
• *Net Position (Cashflow)*: *₹${Math.round(net).toLocaleString()}* (${netStatus})

---

🔍 *TRANSACTION HEALTH & DATA INTEGRITY*
-----------------------------------
• *Successful Records Parsed*: ${transactions.length}
• *Skipped Records (Ingestion Errors)*: ${errors.length}
${formattedErrors}

---

⚠️ *COMPLIANCE RISK & RULES EVALUATION (${alerts.length})*
-----------------------------------
${formattedAlerts}

---

💡 *ADVANCED EXECUTIVE INSIGHT (MOCK)*
-----------------------------------
1. *Operating Costs Spike*: A massive surge of *₹28,000* detected in *Office Operations* for a Herman Miller chair. This is *3x the category average* (~₹933), violating spending limits.
2. *Duplicate Payment Risk*: Duplicate invoice number *INV-2026-005* found twice for vendor *Google LLC* totaling *₹24,000*. Payment processing must be audited to prevent double debiting.
3. *Off-Hours Audit*: An off-hours transaction (Sunday at 2:45 AM) from vendor *Taj Fine Dining* was recorded. Verify whether this was an expense report entry lag or suspicious logging.
4. *Data Hygiene*: Excel file contains format errors in row 12 (unparseable date/amount). Accounting staff should review column formatting guidelines.

*Action Required*: Please review the highlighted *high* and *critical* issues prior to Q2 closure.`;
}

// Execute the test run
runLocalTest().catch((error) => {
  logger.error({ error }, 'Local pipeline integration test crash');
});
